language: cpp

matrix:
  include:
    - os: osx
      addons:
        homebrew:
          packages:
            - libfabric
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

script:
  - cd tests
    #  - make test-local
  - mkdir ../build && cd ../build
  - cmake ..
  - cmake --build . 

