language: cpp

matrix:
  include:
    - os: osx
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      addons:
        apt:
          packages:
            - libfabric-dev
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libfabric-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libfabric-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libfabric-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7
            - clang-5.0
            - libfabric-dev
                  
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cd tests
  - make test-local

