language: cpp

matrix:
  include:
#    - os: osx
#      env:
#        - MATRIX_EVAL="CC=clang && CXX=clang++"
#    
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-5
#      env:
#        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
#    
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-6
#      env:
#        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
#    
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-7
#      env:
#        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
#    
#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-trusty-5.0
#          packages:
#            - g++-7
#            - clang-5.0
#      env:
#        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - clang-6.0
            - libfabric-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"


# before_install:
#  - eval "${MATRIX_EVAL}"
#  - git clone https://github.com/ofiwg/libfabric.git
#  - cd libfabric
#  - ./autogen.sh
#  - ./configure --prefix=$HOME
#  - make
#  - make install
#  - export PKG_CONFIG_PATH=$HOME/lib/pkgconfig
#  - cd ..

script:
#  - export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH
  - cd tests
  - make test-local
  - cat logs/*/latest/usr.0.err*

